---
## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - oodle-ai=https://oodle-ai.github.io/helm-charts
  - vector=https://helm.vector.dev
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
namespace: oodle-monitoring  # Need to set the namespace because we create the secret there
release-label: app.kubernetes.io/instance
