{{- if .Values.fargateLogging.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
    {{- include "oodle-fargate.labels" . | nindent 4 }}
{{- end }}
