apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oodle-fargate.gatewayServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oodle-fargate.labels" . | nindent 4 }}
