{{- $root := . }}
{{- $namespaces := include "oodle-fargate.sidecarNamespaces" . | fromJsonArray }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oodle-fargate.sidecarServiceAccountName" $root }}
  namespace: {{ $ns }}
  labels:
    {{- include "oodle-fargate.labels" $root | nindent 4 }}
{{- end }}
