apiVersion: v2
name: oodle-k8s-observability
description: A Helm chart for Oodle Kubernetes observability stack
type: application
version: 1.0.1
appVersion: "1.0.1"
home: https://github.com/oodle-ai/oodle-k8s-observability-helm
sources:
  - https://github.com/oodle-ai/oodle-k8s-observability-helm
  - https://github.com/oodle-ai/helm-charts
  - https://github.com/oodle-ai/oodle-k8s-auto-instrumentation-helm
maintainers:
  - name: Oodle AI
    url: https://oodle.ai
keywords:
  - monitoring
  - observability
  - metrics
  - prometheus
  - kubernetes
  - eBPF
  - instrumentation

dependencies:
  - name: k8s-monitoring
    version: "^1.0.0"
    repository: "https://oodle-ai.github.io/helm-charts"
    alias: monitoring
    condition: monitoring.enabled
  - name: oodle-k8s-auto-instrumentation
    version: "^1.0.0"
    repository: "https://oodle-ai.github.io/helm-charts"
    alias: auto-instrumentation
    condition: auto-instrumentation.enabled
  - name: vector
    version: "^0.43.0"
    repository: "https://helm.vector.dev"
    alias: vector-agent
    condition: vector-agent.enabled
  - name: vector
    version: "^0.43.0"
    repository: "https://helm.vector.dev"
    alias: vector-aggregator
    condition: vector-aggregator.enabled
  - name: kubernetes-event-exporter
    version: "^3.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: event-exporter
    condition: event-exporter.enabled 
